export const blogData = [
	{
		id: 1,
		title: "Dropshipping: ¿qué es y en qué consiste?",
		linkcontent:"https://blog-y-mas.creatiendaya.com/dropshipping-que-es-y-en-que-consiste/",
		date: "Agost. 20, 2023 ",
		content: "El dropshipping es un modelo de negocio en el que un minorista en línea",
		category: "Dropshipping",
		linkcategory:"https://blog-y-mas.creatiendaya.com/category/dropshipping-noticias-2023/introduccion-al-dropshipping/",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693026062/creatiendaya/drshp-1140x640_dszgpr.png",
	},
	{
		id: 2,
		title: "Proveedores de dropshipping en México",
		linkcontent:"https://blog-y-mas.creatiendaya.com/proveedores-de-dropshipping-en-mexico/",
		date: "Sep. 05, 2023",
		content: "El mundo del comercio electrónico en México está en auge, y los proveedores de dropshipping desempeñan un papel fundamental en este crecimiento.",
		category: "Dropshipping",
		linkcategory:"https://blog-y-mas.creatiendaya.com/category/dropshipping-noticias-2023/introduccion-al-dropshipping/",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693957298/creatiendaya/proveedores-dropshipping-mexico_w98fid.png",
	},
	{
		id: 3,
		title: "Cómo Crear tu Tienda en Shopify: Paso a Paso",
		linkcontent:"https://blog-y-mas.creatiendaya.com/como-crear-tu-tienda-en-shopify/",
		date: "Sep. 2, 2023",
		content: "¿Estás listo para dar vida a tu negocio en línea y empezar a vender tus productos? ¡Genial! Shopify es una plataforma de comercio electrónico fácil de usar",
		category: "Tienda online",
		linkcategory:"https://blog-y-mas.creatiendaya.com/category/blog-de-ecommerce/creacion-de-tiendas-en-linea/",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693957556/creatiendaya/como-crear-tienda-shopify_yoc9by.jpg",
	},
	{
		id: 4,
		title: "Cómo mejorar las fotos en tu tienda en línea para vender más",
		linkcontent:"https://blog-y-mas.creatiendaya.com/como-mejorar-las-fotos-en-tu-tienda/",
		date: "Sep. 2, 2023",
		content: "Cuando compras en línea, ¿qué es lo primero que ves en un producto? ¡Las fotos! Son vitales para que los clientes se sientan atraídos por tus productos.",
		category: "Optimización",
		linkcategory:"https://blog-y-mas.creatiendaya.com/category/blog-de-ecommerce/optimizacion-tiendas-online/",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693957665/creatiendaya/optimizacion-imagenes-tiendas-online_hwt88l.png",
	},
/* 	{
		id: 5,
		title: "What Is The Crypto Volatility Index (CVI)?",
		linkcontent:"#",
		date: "jan. 8, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		linkcategory:"#",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693026062/creatiendaya/drshp-1140x640_dszgpr.png",
	},
	{
		id: 6,
		title: "What Is The Crypto Volatility Index (CVI)?",
		linkcontent:"#",
		date: "Dec. 10, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		linkcategory:"#",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693026062/creatiendaya/drshp-1140x640_dszgpr.png",
	}, */
];
