export const blogData = [
	{
		id: 1,
		title: "Dropshipping: ¿qué es y en qué consiste?",
		linkcontent:"https://blog-y-mas.creatiendaya.com/2023/08/21/dropshipping-que-es-y-en-que-consiste/",
		date: "Agost. 20, 2023 ",
		content: "El dropshipping es un modelo de negocio en el que un minorista en línea",
		category: "dropshipping",
		linkcategory:"https://blog-y-mas.creatiendaya.com/category/dropshipping-noticias-2023/introduccion-al-dropshipping/",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693026062/creatiendaya/drshp-1140x640_dszgpr.png",
	},
	{
		id: 2,
		title: "What Is The Crypto Volatility Index (CVI)?",
		linkcontent:"#",
		date: "Feb. 14, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		linkcategory:"#",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693026062/creatiendaya/drshp-1140x640_dszgpr.png",
	},
	{
		id: 3,
		title: "What Is The Crypto Volatility Index (CVI)?",
		linkcontent:"#",
		date: "Oct. 8, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		linkcategory:"#",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693026062/creatiendaya/drshp-1140x640_dszgpr.png",
	},
	{
		id: 4,
		title: "What Is The Crypto Volatility Index (CVI)?",
		linkcontent:"#",
		date: "Dec. 8, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		linkcategory:"#",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693026062/creatiendaya/drshp-1140x640_dszgpr.png",
	},
	{
		id: 5,
		title: "What Is The Crypto Volatility Index (CVI)?",
		linkcontent:"#",
		date: "jan. 8, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		linkcategory:"#",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693026062/creatiendaya/drshp-1140x640_dszgpr.png",
	},
	{
		id: 6,
		title: "What Is The Crypto Volatility Index (CVI)?",
		linkcontent:"#",
		date: "Dec. 10, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		linkcategory:"#",
		img: "https://res.cloudinary.com/darps1cta/image/upload/v1693026062/creatiendaya/drshp-1140x640_dszgpr.png",
	},
];
